"""Private, user-scoped Gmail API integration."""

from .client import (
    GmailApiClient,
    GmailAttachmentDownload,
    GmailCredentialManager,
    GmailService,
    exchange_code_for_tokens,
)
from .config import (
    GMAIL_API_BASE_URL,
    GMAIL_AUTHORIZATION_URL,
    GMAIL_MAX_ATTACHMENT_BYTES,
    GMAIL_REVOCATION_URL,
    GMAIL_SCOPE,
    GMAIL_TOKEN_URL,
    GmailConfig,
    canonical_gmail_user_id,
    gmail_user_id_for_chat,
    resolve_gmail_redirect_uri,
)
from .errors import (
    GmailAccessDeniedError,
    GmailAlreadyConnectedError,
    GmailApiError,
    GmailAuthError,
    GmailAuthorizationRequiredError,
    GmailConfigurationError,
    GmailCredentialError,
    GmailDraftChangedError,
    GmailError,
    GmailInputError,
    GmailMalformedResponseError,
    GmailMissingScopeError,
    GmailRateLimitError,
    GmailTransportError,
)
from .oauth import (
    DEFAULT_GMAIL_REDIRECT_PATH,
    DEFAULT_GMAIL_REDIRECT_URI,
    GmailOAuthCompletion,
    GmailOAuthError,
    GmailOAuthService,
    begin_gmail_authorization,
    complete_web_authorization,
    create_gmail_authorization_url,
)
from .storage import GmailConnection, SqliteGmailStorage

__all__ = [
    "DEFAULT_GMAIL_REDIRECT_PATH",
    "DEFAULT_GMAIL_REDIRECT_URI",
    "GMAIL_API_BASE_URL",
    "GMAIL_AUTHORIZATION_URL",
    "GMAIL_MAX_ATTACHMENT_BYTES",
    "GMAIL_REVOCATION_URL",
    "GMAIL_SCOPE",
    "GMAIL_TOKEN_URL",
    "GmailAccessDeniedError",
    "GmailAlreadyConnectedError",
    "GmailAttachmentDownload",
    "GmailApiClient",
    "GmailApiError",
    "GmailAuthError",
    "GmailAuthorizationRequiredError",
    "GmailConfig",
    "GmailConfigurationError",
    "GmailConnection",
    "GmailCredentialError",
    "GmailCredentialManager",
    "GmailDraftChangedError",
    "GmailError",
    "GmailInputError",
    "GmailMalformedResponseError",
    "GmailMissingScopeError",
    "GmailOAuthCompletion",
    "GmailOAuthError",
    "GmailOAuthService",
    "GmailRateLimitError",
    "GmailService",
    "GmailTransportError",
    "SqliteGmailStorage",
    "begin_gmail_authorization",
    "canonical_gmail_user_id",
    "complete_web_authorization",
    "create_gmail_authorization_url",
    "exchange_code_for_tokens",
    "gmail_user_id_for_chat",
    "resolve_gmail_redirect_uri",
]
